open-feature/go-sdk-contrib

- providers/flagd/README.md
- providers/flagd/pkg/provider.go
- providers/flagd/pkg/service/grpc/client.go
- providers/flagd/pkg/service/grpc/constructor.go
- providers/flagd/pkg/service/grpc/service.go
Added a CertificatePath option to the GRPCService, if there is an error while loading or none is provided then it defaults back to insecure.NewCredentials()
Updated HTTPS comments as it is now supported by flagd
> added certificate path

- .github/workflows/ci.yaml
- Makefile
- README.md
- hooks/README.md
- hooks/validator/README.md
- hooks/validator/go.mod
- hooks/validator/go.sum
- hooks/validator/pkg/regex/hex_test.go
- hooks/validator/pkg/regex/regex.go
- hooks/validator/pkg/validator/validator.go
- providers/README.md
- providers/flagd/README.md
- providers/flagd/go.mod
- providers/flagd/pkg/provider.go
- providers/flagd/pkg/provider_test.go
- providers/flagd/pkg/service/grpc/client_mock_test.go
- providers/flagd/pkg/service/grpc/constructor_test.go
- providers/flagd/pkg/service/grpc/service.go
- providers/flagd/pkg/service/grpc/service_test.go
- providers/flagd/pkg/service/http/constructor_test.go
- providers/flagd/pkg/service/http/service_test.go
- providers/from-env/README.md
- providers/from-env/go.mod
- providers/from-env/go.sum
- providers/from-env/pkg/eval.go
- providers/from-env/pkg/provider.go
- providers/from-env/pkg/provider_test.go
Signed-off-by: Skye Gill <gill.skye95@gmail.com>
> feat!: rename module to go-sdk-contrib and replace golang-sdk module with go-sdk

- hooks/README.md
- providers/README.md
In one of the [spec prs](https://github.com/open-feature/spec/pull/118) docs were restructured, but the links in this repository were not updated to reflect the changes. This PR simply updates the broken links here
N/A
N/A
N/A
N/A
> docs: fixed broken links in docs

- providers/from-env/README.md
- providers/from-env/pkg/eval.go
Signed-off-by: James Milligan <james@omnant.co.uk>
- updates `variant` to `variants` in the stored flag structure.
- fixes issues with the readme.
- adds casting to range over pointer slice, causing issues with the wrong values being returned for default variants.
https://github.com/open-feature/go-sdk-contrib/issues/45
https://github.com/open-feature/go-sdk-contrib/issues/46
https://github.com/open-feature/go-sdk-contrib/issues/47
> fix!: from-env fixes and readme changes

- providers/flagd/pkg/provider.go
- Fixes nil pointer dereference
Fixes #76
> fix: prevent nil pointer dereference

- providers/flagd/pkg/provider.go
Fixes #84
Changed the log level to warning as we purge the cache, allowing fresh flags to be fetched from the provider. 
Tests were not added as testing the workflow is tough.
> fix: Purge cache if config change event handling fails

- providers/flagd/pkg/provider.go
- providers/flagd/pkg/service/service.go
This was observed while attempting to introduce unit tests on flagD configuration change event handling. 
Further, removed an unused variable within `Service` event handler.
> refactor: Handle context done channel

- providers/go-feature-flag/go.mod
- providers/go-feature-flag/go.sum
- providers/go-feature-flag/pkg/model/eval_response.go
- providers/go-feature-flag/pkg/provider_test.go
- providers/go-feature-flag/testutils/mock_responses/bool_targeting_match.json
- providers/go-feature-flag/testutils/mock_responses/disabled_bool.json
- providers/go-feature-flag/testutils/mock_responses/disabled_float.json
- providers/go-feature-flag/testutils/mock_responses/disabled_int.json
- providers/go-feature-flag/testutils/mock_responses/disabled_string.json
- providers/go-feature-flag/testutils/mock_responses/double_key.json
- providers/go-feature-flag/testutils/mock_responses/flag_not_found.json
- providers/go-feature-flag/testutils/mock_responses/integer_key.json
- providers/go-feature-flag/testutils/mock_responses/invalid_json_body.json
- providers/go-feature-flag/testutils/mock_responses/list_key.json
- providers/go-feature-flag/testutils/mock_responses/object_key.json
- providers/go-feature-flag/testutils/mock_responses/string_key.json
- providers/go-feature-flag/testutils/mock_responses/unknown_reason.json
- providers/go-feature-flag/testutils/module/flags.yaml
This PR is upgrading the GO Feature Flag provider with version `1.0.0`.
Fixes https://github.com/thomaspoignant/go-feature-flag/issues/488
We can close the renovate issue https://github.com/open-feature/go-sdk-contrib/pull/101 because this one is also taking care of the upgrade.
> feat: Update provider to be compatible with GO Feature Flag v1.0.0

- .github/workflows/ci.yaml
- Upgrade ci Go version to 1.19 ([linter was failing on certain 1.19 modules](https://github.com/open-feature/go-sdk-contrib/pull/106))
> chore: upgrade ci go version to 1.19

- providers/flagd/README.md
- providers/flagd/pkg/provider.go
- providers/flagd/pkg/service/client.go
- providers/flagd/pkg/service/service.go
- Exposes WithTLS provider options
- Allow TLS to be used without cert path (default to host system's CAs)
Fixes #42
> feat: exposed WithTLS provider option. Allow tls to be used without cert path (default to host system's CAs)

- tests/flagd/pkg/integration/caching.go
- tests/flagd/pkg/integration/evaluation.go
- tests/flagd/pkg/integration/integration.go
- Allow ProviderOptions to be given to scenario initializations (e.g. for use by TLS testing)
This is a breaking change but as this module is only used internally by go-sdk/flagd the pain of upgrading to the next major version in Go is not worth it.
> feat: allow ProviderOptions to be given to scenario initializations

- providers/flagd/README.md
- providers/flagd/pkg/provider.go
Aligns environment variables with flagd provider spec: https://github.com/open-feature/flagd/blob/main/docs/other_resources/creating_providers.md?plain=1#L117
FLAGD_CACHING_DISABLED environment variable superseded by FLAGD_CACHE. Set FLAGD_CACHE to `disabled` to sustain previous behavior.
Fixes #117
> feat: aligned environment variables application with flagd provider spec

- tests/flagd/pkg/integration/caching.go
- use symbolic links to bypass flagd receiving empty state in file changes (to fix https://github.com/open-feature/flagd/issues/425)
> feat: use symbolic links to bypass flagd receiving empty state in file changes

- hooks/open-telemetry/README.md
- hooks/open-telemetry/go.mod
- hooks/open-telemetry/go.sum
- hooks/open-telemetry/pkg/otel.go
- upgrade go-sdk to v1.3.0
- enforce otel hook to be valid Hook at compile time
Fixes #116
> chore: upgrade go-sdk to v1.3.0. enforce otel hook to be valid Hook at compile time

- release-please-config.json
- extends release notes
- add separate PRs per release artifact
This has been done in other repos and has been well received.
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
> ci: separate PRs for releases and extended release notes

- providers/go-feature-flag/pkg/provider.go
- providers/go-feature-flag/pkg/provider_options.go
- providers/go-feature-flag/pkg/provider_test.go
Support apiKey for GO Feature Flag relay proxy v1.7.0
Fixes https://github.com/thomaspoignant/go-feature-flag/issues/666
> feat: Support apiKey for GO Feature Flag relay proxy v1.7.0

- providers/flagd/pkg/provider_test.go
- introduces unit tests to ensure [go zero values](https://go.dev/tour/basics/12) are returned when the evaluation response is missing the `Value` field for `int` `float` and `bool` evaluations
https://github.com/open-feature/go-sdk-contrib/issues/43
> test: zero value unit tests

- .release-please-manifest.json
- CONTRIBUTING.md
Helps to set the initial version of LD release [1] . Plus adds documentation entry to explain the versioning of releases 
[1]- https://github.com/open-feature/go-sdk-contrib/pull/184
> chore: set LD initial version & update contrib doc

- .github/workflows/release-please.yaml
Fixes failing release workflow [1] due to go environment unavailability. This is required for go-licenses installation.
Further, `go-licenses` require module dependency to be resolved, hence the execution of workspace initialization through make command
[1] - https://github.com/open-feature/go-sdk-contrib/actions/runs/4941452207/jobs/8834069484
> chore: fix release workflow

- hooks/open-telemetry/pkg/otel.go
- hooks/open-telemetry/pkg/otel_test.go
Fixes #204. Consider following Jaeger trace for state & error message
> fix: set error state with a message

- hooks/open-telemetry/README.md
- hooks/open-telemetry/pkg/otel.go
- hooks/open-telemetry/pkg/otel_test.go
Fixes #208
This PR introduces hook build option `WithErrorStatusEnabled`. 
From README,
> **WithErrorStatusEnabled** : enable setting span status to `Error` in case of an error. Default behavior is disabled, 
span status is unset for errors.
Code example
```
openfeature.AddHooks(
otelhooks.NewHook(hooks.WithErrorStatusEnabled()))
```
This gives end-user the control over hook behavior
> feat: otel hook error status override option

- hooks/open-telemetry/pkg/metrics.go
- hooks/open-telemetry/pkg/metrics_test.go
Attempts to address https://github.com/open-feature/go-sdk-contrib/issues/243 
Depreacates `NewMetricsHook(reader metric.Reader)` and introduce `NewMetricsHookForProvider(provider *metric.MeterProvider)`. Non breaking change as we have not yet removed the API
> feat: api change to support more usecases

- .github/component_owners.yml
- .github/workflows/component-owners.yml
- adds component owners, which are added as assignees/reviewers when the file path in question is modified in a PR.
> chore: add component owners

- .github/workflows/release-please.yaml
Attempts to fix recently seen release pipeline failures [1]. The failures started appearing after upgrading `CycloneDX/gh-gomod-generate-sbom`
PR attempts to fix this first by installing Go prior to `CycloneDX/gh-gomod-generate-sbom` 
Also adding quotes to go version in setup-go [2]
[1] - https://github.com/open-feature/go-sdk-contrib/actions/runs/5592620849/jobs/10225319674 
[2] - https://github.com/actions/setup-go#v3
> fix: GitHub action dependency order for sbom gen

- providers/go-feature-flag/pkg/provider_module_test.go
- providers/go-feature-flag/pkg/provider_test.go
- providers/launchdarkly/example_test.go
- providers/launchdarkly/pkg/provider_test.go
- tests/flagd/pkg/integration/caching.go
- tests/flagd/pkg/integration/evaluation.go
Fixes lint issues resulting from Go-SDK 1.5.x update
Change - `SetProvider(provider)` vs `SetProvider(provider) error`
> fix: lint correction on tests

- providers/go-feature-flag/pkg/model/eval_request.go
- providers/go-feature-flag/pkg/provider.go
Problem:
Flag evaluation for same flag using different evaluation context properties can lead to cache key collision.
Solution:
Build cache key considering flag and user evaluation context properties.
[java-sdk PR 369](https://github.com/open-feature/java-sdk-contrib/pull/369)
Run unit tests.
Can test via go-feature-flag instance, while observing logs.
> fix: go-feature-flag sdk - cache key

- hooks/open-telemetry/README.md
- hooks/open-telemetry/pkg/common_test.go
- hooks/open-telemetry/pkg/metrics.go
- hooks/open-telemetry/pkg/metrics_test.go
- hooks/open-telemetry/pkg/traces.go
- hooks/open-telemetry/pkg/traces_test.go
FIxes #294
Adds new OTel hook constructor options for `TraceHook` & `MetricsHooks`
New options `WithAttributeSetterForTraces` & `WithAttributeSetterForMetrics` allow the registration of custom callbacks to extract OTel attributes (dimensions) from flag evaluation metadata 
Callback has the following signature,
```Go
func(openfeature.FlagMetadata) []attribute.KeyValue
```
Along with this change, I have removed deprecated constructors to fascilitate easy future enahancements
> feat!: attribute setter callbacks for otel hooks and remove deprecated constructors 

- .github/workflows/ci.yaml
- .gitmodules
- Makefile
- providers/flagd/e2e/evaluation_test.go
* adds e2e framework to contribs (tests marked with `// +build e2e` at top of file will run with `make e2e`)
* adds standard `evaluation.feature` gherkin tests for flagd provider
gherkin tests for in-memory provider will come next.
See the tests running in the CI: https://github.com/open-feature/go-sdk-contrib/actions/runs/6188614191/job/16800993762?pr=331#step:8:311
> chore: add flagd e2e tests

- providers/flagd-in-process/README.md
- providers/flagd-in-process/pkg/provider.go
Comples part of #393
Adds deprecation notice on flagd in-process provider package.
> feat: deprecate dedicated flagd in-process provider

- providers/flipt/README.md
This fixes open-feature/go-sdk-contrib#397. As seen in the [service implementation](https://github.com/boyvinall/go-sdk-contrib/blob/b4c20b45617e86b6e06c5c5fa68d672ff3efcb9b/providers/flipt/pkg/service/transport/service.go#L152), the scheme is used for http/https or if GRPC then unix:// is used. But plain GRPC should not provide the scheme.
Fixes #397
A demo app can be seen [here](https://github.com/boyvinall/flipt-demo).
> docs: flipt grpc example

- providers/flagd/pkg/provider.go
- providers/flagd/pkg/service/rpc/service.go
- providers/flagd/pkg/service/rpc/service_evaluation_test.go
- fixes #407 
related to: https://github.com/open-feature/go-sdk/issues/238
> fix: nil client causes panic

- providers/flagd/pkg/provider.go
- providers/flagd/pkg/provider_test.go
Fixed https://github.com/open-feature/go-sdk-contrib/issues/417 by adding locks and validations to avoid provider reinitializations. This is done at provider level hence no changes necessary at service level. 
Added a test to validate the logic.
> feat: flagd - make sure provider initialize only once

- providers/flagd/pkg/service/in_process/service.go
- providers/flagd/pkg/service/in_process/service_grpc_test.go
Fixes #416 by adding selector as `scope` in flag evaluation metadata.
> feat: flagd add scope to flag metadata

- providers/flagd/README.md
- providers/flagd/pkg/configuration.go
- providers/flagd/pkg/provider.go
- providers/flagd/pkg/service/in_process/service.go
- providers/flagd/pkg/service/in_process/service_file_test.go
- providers/flagd/pkg/service/in_process/service_grpc_test.go
- providers/flagd/pkg/service/rpc/service.go
Fixes #375 and introduce offline in-process mode for flagd go provider 
Check the below code to see how you can construct the provider in this mode,
```go
provider := flagd.NewProvider(
flagd.WithInProcessResolver(),
flagd.WithOfflineFilePath(OFFLINE_FLAG_PATH))
openfeature.SetProvider(provider)
```
This implementation use flagd file sync implementation [^1]. This minimize code duplications as well as allow us to reuse file watcher logic of flagd itself. 
[^1]: https://github.com/open-feature/flagd/tree/main/core/pkg/sync/file
> feat: flagd offline in-process support with flags sources from file

- .github/workflows/ci.yaml
Bump testbed to release https://github.com/open-feature/flagd-testbed/releases/tag/v0.4.11
> chore: bump testbed version

- providers/flagd/pkg/service/in_process/service.go
- providers/flagd/pkg/service/in_process/service_evaluation_test.go
Improved in-process provider implementation by improving error mapping (flagd evaluator to OF SDK). And partially completes validations of https://github.com/open-feature/flagd/issues/1035
> feat: improve in-process error mapping

- .gitmodules
- providers/flagd/e2e/evaluation_test.go
- providers/flagd/e2e/json_evalutor_test.go
This is something I noticed while validating flagd [#1035](https://github.com/open-feature/flagd/issues/1035)
flagd-specific e2e test submodules were placed in the root level of the repository. This PR move them to flagd folder
> chore: move flagd specific submodule to flagd module

- .release-please-manifest.json
- providers/ofrep/README.md
- providers/ofrep/evaluate.go
- providers/ofrep/go.mod
- providers/ofrep/go.sum
- providers/ofrep/internal/evaluate/flags.go
- providers/ofrep/internal/evaluate/flags_test.go
- providers/ofrep/internal/evaluate/resolver.go
- providers/ofrep/internal/evaluate/resolver_test.go
- providers/ofrep/internal/outbound/http.go
- providers/ofrep/internal/outbound/http_test.go
- providers/ofrep/provider.go
- providers/ofrep/provider_test.go
- release-please-config.json
Fixes #473 and introduce the Go OFREP provider 🎉 
Consider the following code snippet for basic usage,
```go
provider := ofrep.NewProvider(
"http://localhost:8016",
ofrep.WithBearerToken("TOKEN"))
```
This implementation relies on OFREP single flag evaluation endpoint. And there is no caching layer at the current implementation and flag evaluations always rely on remote evaluation results.
I have introduced modules where appropriate which should allow us to expand the implementation with a caching layer and other OFREP extensions that we plan to introduce
> feat: introduce OFREP provider  

- providers/flipt/README.md
Corrects the Flipt provider import statement in the README to one that works.
I also updated the example to use the new SDK syntax for evaluation context creation.
No issues, we just had a question on our Discourse that brought this to our attention:
https://community.flipt.io/t/trouble-getting-started-with-open-feature-go-provider/18/3
> chore(providers/flipt): update README with correct provider import statement

- providers/statsig/README.md
- providers/statsig/pkg/provider.go
- providers/statsig/pkg/provider_test.go
> feat: improve evaluation context to Statsig user conversion

- providers/flipt/README.md
Small doc update to provide the reader with information about using namespaces
n/a
Since we're not just documenting protocols, this adds a new header for `Protocol` to match `Target Namespace`
n/a
n/a
> docs: add namespace docs

- providers/flagd/pkg/configuration.go
- providers/flagd/pkg/provider.go
- providers/flagd/pkg/provider_test.go
closes: #523
The flagd provider defaults to RPC mode and the corresponding port (8013) using the [evaluation proto](https://buf.build/open-feature/flagd/docs/main:flagd.evaluation.v1). If the in-process resolver is selected, it operates in in-process mode using the [sync proto](https://buf.build/open-feature/flagd/docs/main:flagd.sync.v1), but still uses port 8013, instead of defaulting to the correct port (8015, for the sync proto).
We improve the configuration by defaulting to port 8015 if the in-process resolver is selected.
> feat: Default port to 8015 if in-process resolver is used. #523

- providers/launchdarkly/README.md
- Adds details of how OpenFeature contexts are mapped to LaunchDarkly single- and multi-contexts.
n/a
n/a
n/a
n/a
> docs: add details of OpenFeature to LaunchDarkly context mapping

- providers/launchdarkly/README.md
For some reason, the fenced code blocks were showing up as background-highlighted-dark-red when the fenced code blocks had type "json", and were difficult to read.
And my goodness they were ugly!
- fixes appearance of code blocks in launchdarkly provider readme
n/a
n/a
n/a
n/a
> docs: change code in launchdarkly readme from JSON to javascript

- providers/ofrep/provider.go
It is not possible to add a conditional option because it has to be set using the `NewProvider` method.
Ater this PR we should be able to do something like this:
```go
var options = make([]ofrep.Option, 0)
options = append(options, ofrep.WithClient(&http.Client{}))
ofrep.NewProvider("http://localhost:8016", options...)
```
> fix: Make OFREP option public

- providers/ofrep/internal/evaluate/resolver.go
- providers/ofrep/internal/evaluate/resolver_test.go
Should return a parse error if error while parsing
> fix: Should return a parse error if error while parsing

- providers/ofrep/internal/evaluate/flags.go
- providers/ofrep/internal/evaluate/flags_test.go
By default GO when unmarshaling a JSON string GO is mapping all `int` as `float64`.
Before this PR we had only type_mismatch error for int.
> fix: Default GO parsing is float64 for int

- providers/ofrep/internal/evaluate/resolver.go
- providers/ofrep/internal/evaluate/resolver_test.go
`metadata` is not a mandatory field, if the ofrep response does not have a `metadata` field the provider panic.
This PR make it optional to have a `metadata` field.
> fix: Don't panic if metadata not present in the response

- providers/ofrep/internal/evaluate/flags.go
- providers/ofrep/internal/evaluate/flags_test.go
> fix(ofrep): Manage disabled flag

- providers/go-feature-flag/pkg/provider.go
- providers/go-feature-flag/pkg/provider_options.go
…metrics
- Adds `DisableCacheMetrics` to disable cache hit metric collection. Backchannel creates back traffic, which is not always needed or even creates additional workload. 
Fixes #1234523
> feat(fo-feature-flag): add DisableCacheMetrics to disable metrics collector

- .github/component_owners.yml
- Adds @z4kn4fein (ConfigCat) to the component owner's list of the ConfigCat provider. The intention behind this is that we (ConfigCat) would like to mark the provider in this repo as the official ConfigCat OpenFeature Go provider, and we would like to participate in its development and maintenance.
> ci: add z4kn4fein from ConfigCat as component owner

- hooks/open-telemetry/LICENSE
- hooks/validator/LICENSE
- providers/configcat/LICENSE
- providers/flagd/LICENSE
- providers/flagsmith/LICENSE
- providers/flipt/LICENSE
- providers/from-env/LICENSE
- providers/go-feature-flag/LICENSE
- providers/harness/LICENSE
- providers/launchdarkly/LICENSE
- providers/ofrep/LICENSE
- providers/statsig/LICENSE
- providers/unleash/LICENSE
Our license tooling recently started failing (due to updates) because our modules are missing licenses (we only have them at the root). This adds licenses to all modules.
> chore: add license to module

- providers/ofrep/internal/evaluate/flags_test.go
- providers/ofrep/internal/outbound/http.go
- providers/ofrep/internal/outbound/http_test.go
- providers/ofrep/provider_test.go
- This PR fixes the memory leak when using http client.
- It also cleanups few tests and typos.
> fix(ofrep): close http response body after using it

- hooks/open-telemetry/README.md
- Fixes the incorrect function name in the `WithTracesAttributeSetter` example.
- Corrects formatting inconsistencies under the **Options** heading in the Traces hook section.
N/A
- Ensures that the documentation examples are accurate and consistent.
- Improves the readability of the documentation by fixing heading levels.
N/A
- Read through the updated documentation to verify that the function names and formatting are correct.
> docs(main): correct function name and fix formatting in OpenTelemetry Hook documentation

- providers/flagd/README.md
- providers/flagd/pkg/configuration.go
- providers/flagd/pkg/provider.go
- providers/flagd/pkg/provider_test.go
- providers/flagd/pkg/service/in_process/do_nothing_custom_sync_provider.go
- providers/flagd/pkg/service/in_process/service.go
- providers/flagd/pkg/service/in_process/service_custom_sync_provider_test.go
- When the user is using in-process flagd, allows them to supply a `sync.ISync` implementation of their own that can fetch the flag config in any way they like.
This PR provides the capability in Go that was recently added in [Java](https://github.com/open-feature/java-sdk-contrib/pull/900).
> feat: Support supplying a custom sync provider for in-process flagd

- .github/workflows/release-please.yaml
Removing the license extractions because they weren't working properly, and we are already generating a BOM.
Example failures: https://github.com/open-feature/go-sdk-contrib/actions/runs/12591885653/job/35095689159
> ci: remove license extraction steps

- providers/unleash/pkg/provider.go
- providers/unleash/pkg/provider_test.go
- fixes `IntEvaluation` for Unleash provider.
- fixes `TestIntEvaluation` to run correctly and adds `int-flag` to `TestEvaluationMethods`.
Related to https://github.com/open-feature/go-sdk-contrib/pull/465
> fix: IntEvaluation when cannot be parsed

- providers/unleash/pkg/demo_app_toggles.json
- providers/unleash/pkg/provider.go
- providers/unleash/pkg/provider_test.go
- fixes the `TYPE_MISMATCH` error in `IntEvaluation` and `FloatEvaluation` when flags are disabled or missing.
- fixes test cases for `IntEvaluation` and `FloatEvaluation`.
- fixes an issue where test cases are not reading the bootstrap file due to a backup file.
Related to https://github.com/open-feature/go-sdk-contrib/pull/607
> fix: IntEvalution, FloatEvalution when disabled or missing flags

- providers/go-feature-flag/pkg/controller/goff_api.go
- providers/go-feature-flag/pkg/controller/goff_api_test.go
- providers/go-feature-flag/pkg/model/data_collector_request.go
- providers/go-feature-flag/pkg/provider.go
- providers/go-feature-flag/pkg/provider_options.go
- providers/go-feature-flag/pkg/provider_test.go
GO Feature Flag exporter is now supporting adding extra parameters as metadata.
Those parameters are static informations provided during the initialisation to be added in the meta field when calling the exporter.
In the GO Feature Flag we will have those information available in the exporter.
See https://github.com/thomaspoignant/go-feature-flag/issues/2936 for more information.
Fixes https://github.com/thomaspoignant/go-feature-flag/issues/2937
> feat: Support Exporter Metadata

- .golangci.yaml
- Makefile
- Update golangci-lint to v1.64.5
Fixes #628 
`act -j lint`
> chore: update golangci-lint to v1.64.5

- providers/flagd/pkg/provider_test.go
- providers/flagd/pkg/service/in_process/service.go
- fixes potential nil pointer exception when using WithProviderID without WithSelectorID
- adds tests to catch that in the future
> fix(flagd): Fixed possible nil pointer exception with svcMetadata in service.go

- providers/flagd/README.md
- providers/flagd/pkg/configuration.go
- providers/flagd/pkg/provider.go
- providers/flagd/pkg/provider_test.go
- providers/flagd/pkg/service/in_process/service.go
- Exposes the [recently added `GrpcDialOptionsOverride`](https://github.com/open-feature/flagd/pull/1563) in `grpc.Sync` in flagd core (v.0.11.2) as `flagd.WithGrpcDialOptionsOverride(...)` provider option
> feat(flagd): Added WithGrpcDialOptionsOverride provider option

- providers/flagd/README.md
- providers/flagd/pkg/service/in_process/service.go
Add Shutdown support for in-process sync.
This is needed for a follow-up PR that implements custom sync provider which intended to be shutdown.
> feat(flagd): add Shutdown support for in-process sync
