open-feature/go-sdk-contrib

providers/flagd/README.md, providers/flagd/pkg/provider.go, providers/flagd/pkg/provider_test.go, providers/flagd/pkg/service/grpc/constructor.go, providers/flagd/pkg/service/grpc/constructor_test.go, providers/flagd/pkg/service/http/constructor.go, providers/flagd/pkg/service/http/constructor_test.go, providers/flagd/pkg/service/http/service_test.go
https://github.com/open-feature/golang-sdk-contrib/issues/7
=> Changed fladD default port to 8013

README.md, providers/flagd/README.md
https://github.com/open-feature/golang-sdk-contrib/issues/8
=> fixed license link on README

hooks/open-telemetry/README.md, hooks/validator/README.md, providers/from-env/README.md
- brings inline with [go-sdk@v0.6.0 - (awaiting release)](https://github.com/open-feature/go-sdk/pull/95)
Fixes https://github.com/open-feature/go-sdk-contrib/issues/32
=> bring inline with go-sdk@v0.6.0

providers/flagd/pkg/service/client.go
Signed-off-by: jamesmilligan <james@omnant.co.uk>
- removed unused function from flagd provider
#38
=> refactor: removed unused function

Makefile, hooks/open-telemetry/pkg/otel_test.go
Fixes a race condition in a test and runs tests with the race flag by default
Fixes #36
=> fix: race condition in test

Makefile
- refactors the go test action to allow for proper failure
=> fix: test action refactor

providers/flagd/README.md, providers/flagd/pkg/provider.go
Reduces cache stores to a single store with conversion to/from the expected type.
Fixes #65
=> feat(flagd-provider): reduced cache stores to a single store

.github/workflows/lint-pr.yaml, .github/workflows/release-please.yaml, .release-please-manifest.json, Makefile, README.md, release-please-config.json
Signed-off-by: James Milligan <james@omnant.co.uk>
- adds release please action 
- makefile methods `new-hook` and `new-provider` expand the existing `release-please-config.json`, as such all new modules will be tracked
https://github.com/open-feature/go-sdk-contrib/issues/73
=> ci: release please

providers/flagd/pkg/provider.go
Implements a blocking mechanism for use in instances where an application needs to wait until the provider is ready.
Fixes #78
=> feat: created blocking mechanism until provider ready

providers/flagd/README.md, providers/flagd/go.mod, providers/flagd/go.sum, providers/flagd/internal/logger/logger.go, providers/flagd/pkg/provider.go, providers/flagd/pkg/provider_cache_test.go, providers/flagd/pkg/service/service.go
- Introduced configurable structured logging (using logr).
Fixes #88
=> feat: expose ProviderOption to set logr logger & implemented structured logging with levels

tests/flagd/pkg/integration/caching.go
=> fix: only reset state if necessary

providers/flagd/pkg/provider.go
- Applies LRU cache to provider correctly.
https://github.com/open-feature/flagd/issues/457
=> fix: apply lru cache to provider

providers/go-feature-flag/pkg/provider.go, providers/go-feature-flag/pkg/provider_test.go, providers/go-feature-flag/testutils/mock_responses/disabled_bool.json, providers/go-feature-flag/testutils/mock_responses/disabled_float.json, providers/go-feature-flag/testutils/mock_responses/disabled_int.json, providers/go-feature-flag/testutils/mock_responses/disabled_string.json
Rename default variation to keep consistency between all providers.
=> fix: rename default variation to keep consistency

providers/flagd/README.md
=> docs: update flagd port in readme

hooks/open-telemetry/pkg/traces.go
Bring inline with how metrics hook works by using semconv for attribute names; non-breaking as key names are the same.
Also adds feature flag attributes to error span.
N/A
N/A
N/A
N/A
=> refactor(hooks/open-telemetry): Use semconv for trace attribites

providers/flagd-in-process/e2e/evaluation_test.go, providers/flagd-in-process/e2e/json_evalutor_test.go, providers/flagd/e2e/evaluation_test.go, providers/flagd/e2e/json_evalutor_test.go, tests/flagd/pkg/integration/evaluation.go, tests/flagd/pkg/integration/flagd_json_evaluator.go
Utilizing `TestSuiteInitializer` to avoid scernario registration confusion
=> chore: improve e2e test registration

providers/flagd/README.md, providers/flagd/go.mod, providers/flagd/go.sum
Remove duplicate documentation entry
=> docs: remove duplicate in doc

tests/flagd/pkg/integration/integration.go
Improves scenario initialization by using domain-specific providers and cliens
=> feat: domain specific provider for e2e tests

CONTRIBUTING.md, Makefile, providers/flagd/e2e/json_evalutor_test.go, renovate.json
Improved contrib guide with e2e test detials
- Adds makefile targets for e2e tsts
- Document e2e tests 
- Fix & improve docs and exisiting tests
=> chore: improve contrib guide with e2e test details

.github/workflows/ci.yaml, tests/flagd/pkg/integration/flagd_json_evaluator.go
Update to latest test-bed, images and added missing tests
=> chore: update flagd e2e tests

providers/configcat/README.md
- Correcting the version of go-sdk used in the example
=> fix: configcat README example configcat/go-sdk version

providers/from-env/README.md, providers/from-env/pkg/env.go, providers/from-env/pkg/provider.go, providers/from-env/pkg/provider_test.go
Provides a new option for mapping flag names to env variable names
Resolves #526
=> feat(from_env): option for mapping flag to env name

providers/go-feature-flag/README.md
Example wasn't valid go/didn't match the SDK
- adds this new feature
Fixes #1234523
=> docs(GOFF): update examples in the readme

CONTRIBUTING.md, Makefile
- update contributing docs
- remove verbose flag from e2e tests
=> chore: remove verbose flag from e2e tests

providers/flagd/README.md, providers/flagd/e2e/evaluation_test.go, providers/flagd/e2e/json_evalutor_test.go, providers/flagd/pkg/configuration.go, providers/flagd/pkg/provider.go, providers/flagd/pkg/provider_test.go
- adds file resolver to flagd provider
- in-process resolver stays backwards compatible
=> feat(flagd)!: add file mode to flagd provider

renovate.json
migrating to the general openFeature configuration
=> chore: migrate renovate configuration to openFeature config
